# Generated by Django 5.2.7 on 2025-10-22 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=120)),
                ('genero', models.CharField(blank=True, max_length=60)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('publicado', models.DateField()),
                ('stock', models.PositiveIntegerField(default=0)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
